const sampleBookData = [
  {
    title: 'The Great Gatsby',
    subtitle: 'A Novel',
    authors: ['F. Scott Fitzgerald'],
    publishedDate: '1925-04-10',
    publisher: "Charles Scribner's Sons",
    description: 'A novel set in the Roaring Twenties.',
    language: 'en',
    pageCount: 218,
    coverImage: 'https://example.com/great-gatsby.jpg',
    ratings: {
      google: 4.5,
    },
    isbn: '9780743273565',
    urls: {
      google: 'https://books.google.com/books?id=great-gatsby',
    },
  },
  {
    title: 'To Kill a Mockingbird',
    subtitle: '',
    authors: ['Harper Lee'],
    publishedDate: '1960-07-11',
    publisher: 'J.B. Lippincott & Co.',
    description: 'A novel about racial injustice in the Deep South.',
    language: 'en',
    pageCount: 281,
    coverImage: 'https://example.com/to-kill-a-mockingbird.jpg',
    ratings: {
      google: 4.8,
    },
    isbn: '9780061120084',
    urls: {
      google: 'https://books.google.com/books?id=to-kill-a-mockingbird',
    },
  },
  {
    title: '1984',
    subtitle: 'A Dystopian Novel',
    authors: ['George Orwell'],
    publishedDate: '1949-06-08',
    publisher: 'Secker & Warburg',
    description: 'A novel about a dystopian future.',
    language: 'en',
    pageCount: 328,
    coverImage: 'https://example.com/1984.jpg',
    ratings: {
      google: 4.7,
    },
    isbn: '9780451524935',
    urls: {
      google: 'https://books.google.com/books?id=1984',
    },
  },
  {
    title: 'Pride and Prejudice',
    subtitle: '',
    authors: ['Jane Austen'],
    publishedDate: '1813-01-28',
    publisher: 'T. Egerton, Whitehall',
    description: 'A romantic novel about manners and marriage.',
    language: 'en',
    pageCount: 279,
    coverImage: 'https://example.com/pride-and-prejudice.jpg',
    ratings: {
      google: 4.6,
    },
    isbn: '9780141040349',
    urls: {
      google: 'https://books.google.com/books?id=pride-and-prejudice',
    },
  },
  {
    title: 'The Catcher in the Rye',
    subtitle: '',
    authors: ['J.D. Salinger'],
    publishedDate: '1951-07-16',
    publisher: 'Little, Brown and Company',
    description: 'A novel about teenage rebellion and angst.',
    language: 'en',
    pageCount: 214,
    coverImage: 'https://example.com/catcher-in-the-rye.jpg',
    ratings: {
      google: 4.3,
    },
    isbn: '9780316769488',
    urls: {
      google: 'https://books.google.com/books?id=catcher-in-the-rye',
    },
  },
  {
    title: 'Moby-Dick',
    subtitle: 'Or, The Whale',
    authors: ['Herman Melville'],
    publishedDate: '1851-10-18',
    publisher: 'Harper & Brothers',
    description: 'A novel about the voyage of the whaling ship Pequod.',
    language: 'en',
    pageCount: 635,
    coverImage: 'https://example.com/moby-dick.jpg',
    ratings: {
      google: 4.2,
    },
    isbn: '9780142437247',
    urls: {
      google: 'https://books.google.com/books?id=moby-dick',
    },
  },
  {
    title: 'War and Peace',
    subtitle: '',
    authors: ['Leo Tolstoy'],
    publishedDate: '1869',
    publisher: 'The Russian Messenger',
    description: 'A novel about the French invasion of Russia.',
    language: 'ru',
    pageCount: 1225,
    coverImage: 'https://example.com/war-and-peace.jpg',
    ratings: {
      google: 4.4,
    },
    isbn: '9780199232765',
    urls: {
      google: 'https://books.google.com/books?id=war-and-peace',
    },
  },
  {
    title: 'The Hobbit',
    subtitle: 'There and Back Again',
    authors: ['J.R.R. Tolkien'],
    publishedDate: '1937-09-21',
    publisher: 'George Allen & Unwin',
    description: 'A fantasy novel about the journey of Bilbo Baggins.',
    language: 'en',
    pageCount: 310,
    coverImage: 'https://example.com/the-hobbit.jpg',
    ratings: {
      google: 4.7,
    },
    isbn: '9780547928227',
    urls: {
      google: 'https://books.google.com/books?id=the-hobbit',
    },
  },
  {
    title: 'The Lord of the Rings',
    subtitle: '',
    authors: ['J.R.R. Tolkien'],
    publishedDate: '1954-07-29',
    publisher: 'George Allen & Unwin',
    description: 'A fantasy novel about the quest to destroy the One Ring.',
    language: 'en',
    pageCount: 1178,
    coverImage: 'https://example.com/lord-of-the-rings.jpg',
    ratings: {
      google: 4.9,
    },
    isbn: '9780618640157',
    urls: {
      google: 'https://books.google.com/books?id=lord-of-the-rings',
    },
  },
  {
    title: "Harry Potter and the Philosopher's Stone",
    subtitle: '',
    authors: ['J.K. Rowling'],
    publishedDate: '1997-06-26',
    publisher: 'Bloomsbury',
    description: 'A fantasy novel about a young wizard named Harry Potter.',
    language: 'en',
    pageCount: 223,
    coverImage: 'https://example.com/harry-potter.jpg',
    ratings: {
      google: 4.8,
    },
    isbn: '9780747532699',
    urls: {
      google: 'https://books.google.com/books?id=harry-potter',
    },
  },
];

export default sampleBookData;
