packages:
  - apps/*
ignoredBuiltDependencies:
  - '@prisma/client'
onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@swc/core'
  - '@vercel/speed-insights'
  - esbuild
  - nx
  - prisma
  - sharp
