import {
    Loader2,
    X,
    Menu,
    type Icon as LucideIcon,
    ChevronDown,
    ChevronLeft,
    User,
    ChevronRight,
    ArrowRight,
    Book,
    BookOpen,
    Dot,
    LayoutGrid,
    LayoutList,
    PieChart,
    Search,
    Trash,
    Library,
    ListPlus,
    Plus,
    Clock,
    ArrowDown,
    Heart,
    Pencil,
    Check,
    AlignLeft,
    CheckCircle2,
    FileDown,
    FileUp,
    BanIcon,
    Bookmark,
    MessageSquare,


} from "lucide-react";
import { DotsVerticalIcon, LayoutIcon } from "@radix-ui/react-icons";

export type Icon = LucideIcon;

export const Icons = {
    close: X,
    spinner: Loader2,
    chevronDown: ChevronDown,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    arrowRight: ArrowRight,
    menu: Menu,
    user: User,
    book: Book,
    read: CheckCircle2,
    bookOpen: BookOpen,
    dot: Dot,
    layoutGrid: LayoutGrid,
    layoutList: LayoutList,
    pieChart: PieChart,
    search: Search,
    delete: Trash,
    library: Library,
    log: ListPlus,
    plus: Plus,
    date: Clock,
    down: ArrowDown,
    heart: Heart,
    edit: Pencil,
    check: Check,
    shelf: AlignLeft,
    notes: AlignLeft,
    import: FileDown,
    export: FileUp,
    more: DotsVerticalIcon,
    abondoned: BanIcon,
    save: Bookmark,
    comment: MessageSquare,
    kanban: LayoutIcon,


};
